version: "2.1"
services:
  server:
    build: .
    ports:
      - "8080:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=pass
    # volumes:
      # - ./app:/server # volume in host -> $(pwd)/app

  db:
    image: mongo
    command: mongod --smallfiles
    volumes:
      - ./mongo/db:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    healthcheck:
      test: ["CMD", "echo", "show dbs", "|", "mongo"]
      interval: 30s
      timeout: 10s
      retries: 3
