version: "2"
services:
  server:
    build: .
    ports:
      - "8080:3000"
    depends_on:
      - db
    volumes:
      - ./app:/server # volume in host -> $(pwd)/app

  db:
    image: mongo
    command: mongod --smallfiles
    ports:
      - "27017:27017"
