apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: node-mongo-app
    tier: db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-mongo-app
        tier: db
        track: stable
    spec:
      containers:
        - name: mongo
          image: "mongo"
          ports:
            - name: http
              containerPort: 27017